name: Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo "Welcome to the Github Actions workshop !"

  unit-test:
    runs-on: ubuntu-latest
    container: ghcr.io/epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit-tests
        run: |
          echo "Running unit tests..."
          # Replace with your actual test command
          ./unit_tests

      - name: Run coverage
        run: |
          echo "Running coverage..."
          # Replace with your actual coverage command
          ./coverage
